### ISSUE TITLE
xvfb on Windows

### ISSUE THREAD

**Issue by DevAmiyo** [ItzCuteAkemi/pptr-youtube-music#1]
> ```bash
> 'xvfb-run' is not recognized as an internal or external command, operable program or batch file.
> ```
#### How to install `xvfb` on Windows?

**Comment by sprucecellodev125** [comment]
There's no Xvfb in Windows. However I updated it to make headless chrome really headless. Try git pull now with latest commit

**Comment by sprucecellodev125** [comment]
Oops. Incase if you still had another issue
sry for late reply

**Comment by DevAmiyo** [comment]
> There's no Xvfb in Windows. However I updated it to make headless chrome really headless. Try git pull now with latest commit

kk
